### ISSUE TITLE
请问你是如何解决angular 8不兼容PrimeNG 7的?

### ISSUE THREAD

**Issue by chliuqi** [damoqiongqiu/NiceFish#6]
请问你是如何解决angular8不兼容PrimeNG7的?
`
ERROR in ../node_modules/primeng/components/table/table.d.ts:5:27 - error TS2307: Cannot find module '@angular/core/src/metadata/lifecycle_hooks'.

5 import { OnDestroy } from '@angular/core/src/metadata/lifecycle_hooks';
`

**Comment by damoqiongqiu** [comment]
已解决，请看 package.json 配置。
